version: "3.7"
services:
  db:
    image: "postgres:alpine"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    restart: always
  redis:
    image: redis

  web:
    environment:
      DATABASE_URL_DEV: "postgres://postgres:password@db:5432/postgres"
      DEV_DATABASE_URL: "postgres://postgres:password@db:5432/postgres"
      DATABASE_URL: "postgres://postgres@db:5432/postgres"
      REDIS_URL: "redis://redis:6379"
      TOKEN: ${TOKEN}
      PORT: "3000"
      API_KEY: ${API_KEY}
      baseUrl: "localhost:3000"
      FROM_EMAIL: ${FROM_EMAIL}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FB_CLIENT_ID: ${FB_CLIENT_ID}
      FB_CLIENT_SECRET: ${FB_CLIENT_SECRET}
    build: .
    depends_on:
      - db
      - redis
    ports: 
      [3000:3000]
#    restart: always

    
